[package]
name = "config-space-manager-esp-nvs"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "ESP NVS backend for config-space-manager"
repository = "https://github.com/iobewi/config-space-manager"
keywords = ["embedded", "configuration", "esp32", "nvs", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = []
esp32c3 = ["esp-flash-access/esp32c3", "esp-nvs/esp32c3"]
esp32s3 = ["esp-flash-access/esp32s3", "esp-nvs/esp32s3"]

[dependencies]
config-space-manager = { path = "../.." }
esp-flash-access = { git = "https://github.com/iobewi/esp-storage-manager", rev = "b7fb2f6" }
embedded-storage = "0.3.1"
esp-nvs = "0.5.0"
esp-storage = "0.9.0"
log = { version = "0.4.29", default-features = false }
