[package]
name = "config-space-manager-esp-nvs"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "ESP NVS backend for config-space-manager"
repository = "https://github.com/iobewi/config-space-manager"
keywords = ["embedded", "configuration", "esp32", "nvs", "no-std"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = []
esp32c3 = ["espbewi-nvs/esp32c3"]
esp32s3 = ["espbewi-nvs/esp32s3"]

[dependencies]
config-space-manager = { path = "../.." }
espbewi-flash = { git = "https://github.com/iobewi/espbewi", rev = "95a99b9605ea4d7ebfba4f2c94f13a7b403b82c0", package = "espbewi-flash" }
espbewi-nvs = { git = "https://github.com/iobewi/espbewi", rev = "95a99b9605ea4d7ebfba4f2c94f13a7b403b82c0", package = "espbewi-nvs" }
esp-nvs = "0.5.0"
log = { version = "0.4.29", default-features = false }
