name: Rust

on:
  push:
  pull_request:

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.88.0"
      - run: cargo test -p config-space-manager
      - run: cargo check -p config-space-manager --lib

  esp32c3-storage-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.88.0"
          targets: riscv32imc-unknown-none-elf
          components: clippy
      - run: cargo check -p config-space-manager-esp-storage --features esp32c3 --target riscv32imc-unknown-none-elf
      - run: cargo clippy -p config-space-manager-esp-storage --features esp32c3 --target riscv32imc-unknown-none-elf -- -D warnings
